db:
  adapter: postgresql
  host: localhost
  user: postgres
pagination:
  page_size: 10
app:
  secret: secret

dependencies:
  auth_service_url: http://localhost:3010/v1/auth
  geocoder_service_url: http://localhost:3011/geocoder
